service: notionfyer
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  timeout: 60
  environment:
    NOTION_TOKEN: ${env:NOTION_TOKEN}
    NOTION_SPENDINGS_DB: ${env:NOTION_SPENDINGS_DB}
    NOTION_BUDGET_LIMIT_DB: ${env:NOTION_BUDGET_LIMIT_DB}
    SNS_TOPIC_ARN: ${env:SNS_TOPIC_ARN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - "*"

functions:
  notionfyer:
    handler: src/index.handler
    events:
      - schedule: cron(0,30 6-23 ? * * *)

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
